### ISSUE TITLE
heightmap adjust script not working

### ISSUE THREAD

**Issue by samiul-hoque** [mattwach/cnc_pcb_tools#1]
Running candle_heightmap_adjust.py throws error. 

I'm running:
`python candle_heightmap_adjust.py --input height.map --offset 0.1`
Output I'm getting:
`With 20 rows, expected 23 lines in the file.  Found 8 lines instead`

Here's the heightmap file that was saved by candle as height.map
```
0.00;0.00;76.24;44.49
8;5;-1.00;1.00
0;20;20
0;-0.10599999999999987;-0.10899999999999999;-0.080000000000000071;-0.072999999999998622;-0.088999999999998636;-0.1039999999999992;-0.125
-0.032999999999999474;-0.1639999999999997;-0.18900000000000006;-0.17300000000000004;-0.16799999999999926;-0.17300000000000004;-0.18900000000000006;-0.20599999999999952
-0.082999999999998408;-0.21299999999999919;-0.25099999999999945;-0.23299999999999876;-0.23099999999999987;-0.24899999999999878;-0.24899999999999878;-0.24899999999999878
-0.11299999999999955;-0.25099999999999945;-0.28099999999999881;-0.28399999999999892;-0.27299999999999969;-0.28799999999999848;-0.29299999999999926;-0.29099999999999859
-0.13299999999999912;-0.27099999999999902;-0.29999999999999893;-0.29299999999999926;-0.29299999999999926;-0.31099999999999994;-0.30899999999999928;-0.30499999999999972
```

**Comment by mattwach** [comment]
I see.  The tool was looking at interpolation settings instead of grid settings.  I always have them set the same and didn't see the bug because of that.

I updated the tool to look at grid settings instead (2nd row, columns 1 and 2).  I also tested the new tool on the data you provided and the output looks good.  Please try the latest version, thanks!

**Comment by samiul-hoque** [comment]
Thanks so much for the fast fix! I just tested as well, it's working great!
